/*
 * -----------------------------------------------------------------------
 * File: config.toml
 * Creation Time: Jan 31st 2024, 11:46 pm
 * Author: Saurabh Zinjad
 * Developer Email: saurabhzinjad@gmail.com
 * Copyright (c) 2023-2024 Saurabh Zinjad. All rights reserved | https://github.com/Ztrimus
 * -----------------------------------------------------------------------
 */

